export function getCurrentCountryLanguage(): string[];
export function useBlockConfig(block: HTMLElement, BLOCK_CONFIG: BlockConfig, fieldExtractors?: Record<string, (row: HTMLElement, index: number, rows: HTMLElement[]) => any>): Record<string, { text: string; node: HTMLElement | null; picture: HTMLPictureElement | null; img: HTMLImageElement | null }>;
export function createImageWithModal(referenceLink: string, alt: string, smartCrop: string, mobileReferenceLink?: string, attachModal?: boolean, eager?: boolean): HTMLImageElement;
export function createFigureWithModal(options: { referenceLink: string; alt: string; smartCrop: string; mobileReferenceLink?: string; attachModal?: boolean; eager?: boolean }): HTMLImageElement;
export function mapPath(path: string): string;
export function fetchSVG(url: string): Promise<string>;
export function normalizeForMatch(str: string): string;
export function parseItemTags(tagsContent: string, { normalizeFn, getDisplayName }: { normalizeFn: (str: string) => string; getDisplayName: (str: string) => string }): string[];
export function matchesTagFilters(selectedFilters: string[], itemTagMap: Record<string, string[]>): boolean;
export function createItemMatcher({ getDisplayName, block }: { getDisplayName: (str: string) => string; block: HTMLElement }): (item: any) => boolean;
export function ensureContainer(parent: HTMLElement, selector: string, appendFn?: ((element: HTMLElement) => void) | null): HTMLElement;
export function mapTagIdToPath(id: string): string;
export function mapTaxonomy(data: any): any;
export function fetchTaxonomy(language: string): Promise<any>;
export function getTaxonomy(language: string): Promise<any>;
export function getTaxonomyMapByPath(language: string): Promise<any>;
export function videoToOriginalRendition(url: string): string;
export function getTaxonomyMapById(language: string): Promise<any>;
export function loadItemBlocks(parentBlock: HTMLElement, blockClassName: string): Promise<void>;
export async function getDictionary(): Prmomise<any> | null;